### ISSUE TITLE
[node.js로 API 만들기] 가이드 내용 추가 요청

### ISSUE THREAD

**Issue by seohyun0120** [kyeahen/ExpressionRekognitionMusicService#1]
[node.js로 API 만들기](https://github.com/kyeahen/ExpressionRekognitionMusicService/blob/master/Guide/node.js%EB%A1%9C%20API%20%EB%A7%8C%EB%93%A4%EA%B8%B0.md) 6단계에 아래 내용을 추가하면 좋을 것 같아요

```
$ cd [해당 디렉토리 위치]
$ zip -r ../[해당 폴더명] ./
```

`[해당폴더명].zip` 파일이 생성되었다면 성공입니다.

**Comment by kyeahen** [comment]
내용 추가했습니다! 감사합니다:-)

**Comment by kyeahen** [comment]
내용 추가했습니다! 감사합니다:-)
